const { getTalker, putTalker } = require('./utils');
const { BAD_REQUEST, TALKER_NOT_FOUND, EMAIL_REQUIRED,
EMAIL_FORMAT_INVALID, PASSWORD_REQUIRED, MIN_PASSWORD_LENGTH, TOKEN_NOT_FOUND,
TOKEN_INVALID, NAME_REQUIRED, MIN_NAME_LENGTH, AGE_REQUIRED,
MIN_AGE_REQUIRED, TALK_REQUIRED,
WATCHED_AT_REQUIRED, WATCHED_AT_FORMAT_INVALID, RATE_REQUIRED, RATE_RANGE,
} = require('./constants');

module.exports = {
getTalker,
putTalker,
BAD_REQUEST,
TALKER_NOT_FOUND,
EMAIL_REQUIRED,
EMAIL_FORMAT_INVALID,
PASSWORD_REQUIRED,
MIN_PASSWORD_LENGTH,
TOKEN_NOT_FOUND,
TOKEN_INVALID,
NAME_REQUIRED,
MIN_NAME_LENGTH,
AGE_REQUIRED,
MIN_AGE_REQUIRED,
TALK_REQUIRED,
WATCHED_AT_REQUIRED,
WATCHED_AT_FORMAT_INVALID,
RATE_REQUIRED,
RATE_RANGE,
};
